### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by madmod**
:smile:

### CODE REVIEW

**Comment by swissmanu** [comment]
thx! 😁

**Comment by sushilks** [comment]
@swissmanu Looks like these changes are not getting pulled when you use "npm install" 
Probably you will need to bump up the version and publish it again on npm. 

BTW Thanks for the work, it's very useful. I did some workflow modification for my use case on it.

**Comment by swissmanu** [comment]
i'm currently on vacation, sorry. i hope i find some time in the first week of august.

**Comment by madmod** [comment]
No worries npm works fine with my fork for now. :smiley:

**Pull request merged**
